### ISSUE TITLE
Inconsistent key state behavior on windows

### ISSUE THREAD

**Issue by jlbeard84** [bferguson3/msx2tools#27]
On windows, the key.state doesn't appear to be matching the documentation (as in 0x0004 == 'Ctrl'). Left Ctrl seems to be giving a value of 8, and Right Ctrl a value of 262152.

![image](https://user-images.githubusercontent.com/4313198/57500019-c1eeb280-72af-11e9-8b7a-3ba5feb55962.png)

![image](https://user-images.githubusercontent.com/4313198/57500106-0e39f280-72b0-11e9-8704-566a1881b44c.png)

**Comment by bferguson3** [comment]
Closing for now, & 4 seems to work cross platform
